#!/usr/bin/env bash

#
# powermenu - a very simple rofi powermenu
#
# Copyright (C) 2025 Johannes Kamprad
#
# SPDX-License-Identifier: GPL-3.0-or-later

# needs rofi config:
# $HOME/.config/rofi/powermenu.rasi
# set to be used in i3wm

ROFI_THEME="${HOME}/.config/rofi/powermenu.rasi"
# Define possible lock scripts/commands (edit this list as you like)

# Menu entries
chancel=" Cancel"
logout="  Logout"
reboot="  Reboot"
shutdown="  Shutdown"


# Add lock only if script is found
if lockcmd="$(find_lock_script)"; then
    options="$chancel\n$logout\n$reboot\n$shutdown"
else
    options="$chancel\n$logout\n$reboot\n$shutdown"
fi

chosen="$(echo -e "$options" | rofi -dmenu -i -p "Power Menu" \
    -theme $ROFI_THEME)"

case $chosen in
    "$cancel"|"")
        exit 0
        ;;
    "$logout")
        i3-msg exit
        ;;
    "$reboot")
        systemctl reboot
        ;;
    "$shutdown")
        systemctl poweroff
        ;;
esac
