#! /bin/bash
#
# v17 - 25-10-25 Endeavour OS 

System='EndeavourOS'

#Colour Varibles
RED='\033[0;31m'
BRED='\033[1;31m'         # Bold Red
BYell='\033[1;33m'         # Bold Yellow
NC='\033[0m' # No Color

clear

#printf "${RED}Show all running services${NC}\n"
# with  echo command use the -e flag to allow backslash escapes.
echo -e  "${BYell}${System} System Information & Running services ${NC}"
echo

echo -e  "${BRED}Kernel Release:${NC}   " `uname -r`
#echo -e  "${BRED}Distribution:${NC}     " `cat /etc/os-release | grep PRETTY_NAME | awk '{printf "%s %s %s %s\n", $2,$3,$4,$5}'`
echo -e  "${BRED}Distribution:${NC}     " `lsb_release -d -s`
echo

# Show who is logged on and what they are doing.
# but remove first line of output of w which is uptime
#echo -e  "${BRED}Logged on users & processes${NC}"
#w | awk '{if(NR>1)print}'
#echo

# Remove the IPv6 addresses
echo -e  "${BRED}IP Address:${NC}       " `ip addr show enp0s8 | grep inet | awk '{ print $2; }' | sed 's/\/.*$//' | grep -v :`
echo -e  "${BRED}Network Hostname:${NC} " `uname --nodename`
#lsb_release -a
echo

echo -e  "${BRED}Uptime:${NC}           " `uptime | cut -c 13-75`
echo

# Remove Swap line
echo -e  "${BRED}Memory Usage${NC}"
free -h | grep -v Total 
echo

echo -e  "${BRED}Disk Usage${NC}"
df -h | grep Filesystem | awk '{printf "%-15s %-7s %-7s %-7s %-7s\n", $1,$2,$3,$4,$5}'
df -h | grep /dev/sda2  | awk '{printf "%-15s %-7s %-7s %-7s %-7s\n", $1,$2,$3,$4,$5}'
echo

#read -rsn1 -p"Press any key to continue";echo

echo -e  "${BRED}Running system daemons/services${NC}"
# systemctl -t service --no-pager --no-legend | grep -v exited | grep -v systemd | awk  '{printf "%-33s - %s %s %s %s %s %s\n",  $1,$5,$6,$7,$8,$9,$10}'
systemctl -t service --no-pager --no-legend | grep running | awk  '{printf "%-35s - %s %s %s %s %s %s %s\n",  $1,$5,$6,$7,$8,$9,$10,$11}'

echo
echo -e  "${BRED}Running user daemons/services${NC}"
systemctl --user -t service --no-pager --no-legend | grep running | awk  '{printf "%-35s - %s %s %s %s %s %s %s\n",  $1,$5,$6,$7,$8,$9,$10,$11}'
echo

echo -e  "${BRED}Failed daemons/services${NC}"
systemctl list-units --failed
