#!/bin/bash

# setting up new version of sublime_text

#Colour Varibles
RED='\033[0;31m'
BRED='\033[1;31m'         # Bold Red
BYell='\033[1;33m'         # Bold Yellow
NC='\033[0m' # No Color

clear

echo -e  "${BYell} New version of sublime text ${NC}"
echo

echo -e  "${BRED}Setting up system permissions on sublime text${NC}"
echo

cd $HOME/Downloads/ 
sudo chmod 755 sublime_text 
sudo chown root sublime_text 
sudo chgrp root sublime_text 

echo -e  "${BRED}If sublime_text.old exists delet it${NC}"
[[ -f /opt/sublime_text/sublime_text.old  ]] && sudo rm /opt/sublime_text/sublime_text.old
echo

echo -e  "${BRED}Renaming sublime_text to sublime_text.old ${NC}"
echo
sudo mv /opt/sublime_text/sublime_text  /opt/sublime_text/sublime_text.old 
echo

echo -e  "${BRED}Moving new sublime_text to /opt directory${NC}"
echo
sudo mv sublime_text /opt/sublime_text/

